Roomax/Roomax/Areas/BackOffice/Controllers/DashboardController.cs
using Roomax.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomax.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class DashboardController : Controller
    {
        // GET: BackOffice/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

Roomax/Roomax/Controllers/SharedController.cs
using Roomax.Areas.BackOffice.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomax.Controllers
{
    public class SharedController : BaseController
    {
        // GET: Shared
        [ChildActionOnly]
        public ActionResult TopFive()
        {
            var rooms = db.Rooms.OrderByDescending(x => x.Price).Take(5);
            return View("_TopFive", rooms);
        }
    }
}

Roomax/Roomax/Controllers/UsersController.cs
using Roomax.Data;
using Roomax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Roomax.Utils;

namespace Roomax.Controllers
{
    public class UsersController : Controller
    {
        private RoomaxDbContext db = new RoomaxDbContext();
        // GET: Users
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Civilities = db.Civilities.ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                user.Password = user.Password.HashMD5();

                //enregistrer en bdd
                db.Users.Add(user);
                db.SaveChanges();

                //redirection
                TempData["Message"] = $"L'utilisateur {user.FirstName} est enregistré.";
                return RedirectToAction("Index", "Home");

            }
            ViewBag.Civilities = db.Civilities.ToList();
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose(); //libère la connexion à la BDD
            base.Dispose(disposing);
        }
    }
}

Roomax/Roomax/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Roomax.css" rel="stylesheet" />
</head>
<body>
    <div class="container ">
        <nav class="row navbar navbar-expand-lg bg-info">
            <ul class="nav">
                <li><h1 class="lead text-white">Roomax</h1></li>
                <li><a href="@Url.Action("Index", "Home")" class="col-2 text-white">Accueil</a></li>
                <li><a href="@Url.RouteUrl("AboutRoute")" class="col-2 text-white">A propos</a></li>
                <li><a href="@Url.Action("Create", "Users")" class="col-2 text-white">Nouvel Utilisateur</a></li>
                <li><a href="@Url.Action("Index", "Dashboard", new { area = "BackOffice" })" class="col-2 text-white">Back Office</a></li>
            </ul>
        </nav>

        @RenderBody()
    </div>
    <div class="container">
        <div class="row">
            <footer class="bg-light w-100">
                &copy; POEC Rouen 2018
                @Html.Action("TopFive", "Shared")
            </footer>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("SectionScripts", false)
</body>
</html>

Roomax/Roomax/Views/Shared/_LayoutForm.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-3"></div>
    <div class="card col-6">
        <div class="card-header">
            @RenderSection("SectionTitle", true)
        </div>
        <div class="card-body">
            @RenderBody()
        </div>
    </div>
    <div class="col-3"></div>
</div>


@section SectionScripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("SectionScripts", false)
}

Roomax/Roomax/Views/Shared/_TopFive.cshtml
@model IEnumerable<Roomax.Models.Room>

@{
    Layout = null;
}




<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-3">
            <p>@item.Name</p>
            <p>@item.Price €</p>
        </div>

    }
</div>