Roomax/Roomax/Areas/BackOffice/Controllers/AuthenticationController.cs
using Roomax.Areas.BackOffice.Models;
using Roomax.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Roomax.Utils;
using Roomax.Filters;


namespace Roomax.Areas.BackOffice.Controllers
{

    public class AuthenticationController : BaseController
    {
        // GET: BackOffice/Authentication/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: BackOffice/Authentication/Login
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Login(AuthenticationLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var passwordHash = model.Password.HashMD5();
                var user = db.Users.SingleOrDefault(x => x.Mail == model.Login && x.Password == passwordHash);
                if (user == null)
                {
                    TempData["Message"] = "Utilisateur ou Mot de passe incorrect";
                    ModelState.AddModelError("", "Utilisateur ou Mot de passe incorrect");
                    return View(model);
                }
                else
                {
                    Session.Add("USER_BO", user);
                    Session["USER_NAME"] = user.FirstName;
                    TempData["Message"] = "Login effectué";
                    return RedirectToAction("Index", "Dashboard", new { area = "BackOffice" });
                }
                
            }
            return View(model);


        }

        // GET : BackOffice/Authentication/Logout
        [AuthenticationFilter]
        public ActionResult Logout()
        {
            Session.Clear();
            TempData["Message"] = "Vous êtes déconnecté";
            
            return RedirectToAction("Index", "Home", new { area = "" });
        }
    }
}

Roomax/Roomax/Areas/BackOffice/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roomax.Data;
using Roomax.Filters;
using Roomax.Models;

namespace Roomax.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class CategoriesController : BaseController
    {
        // GET: BackOffice/Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: BackOffice/Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: BackOffice/Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BackOffice/Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                this.DisplayMessage("Catégorie enregistrée", MessageType.SUCCESS);
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: BackOffice/Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: BackOffice/Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "Catégorie modifiée";
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: BackOffice/Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: BackOffice/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            TempData["Message"] = "Catégorie supprimée";
            TempData["TypeMsg"] = "alert alert-success";
            return RedirectToAction("Index");
        }
    }
}

Roomax/Roomax/Areas/BackOffice/Controllers/DashboardController.cs
using Roomax.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomax.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class DashboardController : Controller
    {
        // GET: BackOffice/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

Roomax/Roomax/Areas/BackOffice/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roomax.Data;
using Roomax.Filters;
using Roomax.Models;

namespace Roomax.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class RoomsController : BaseController
    {
        // GET: BackOffice/Rooms
        public ActionResult Index()
        {
            var rooms = db.Rooms.Include(r => r.User).Include(r => r.Category);
            return View(rooms.ToList());
        }

        // GET: BackOffice/Rooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Include(r => r.User).Include(r => r.Category).SingleOrDefault(x => x.ID == id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // GET: BackOffice/Rooms/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.Users, "ID", "LastName");
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: BackOffice/Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Capacity,Price,Description,CreatedAt,UserID,CategoryID")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.Users, "ID", "LastName", room.UserID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", room.CategoryID);
            TempData["Message"] = "Salle créée";
            return View(room);
        }

        // GET: BackOffice/Rooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Include(x => x.Files).SingleOrDefault(x => x.ID == id);
            if (room == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "ID", "LastName", room.UserID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", room.CategoryID);
            return View(room);
        }

        // POST: BackOffice/Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Capacity,Price,Description,CreatedAt,UserID, CategoryID")] Room room)
        {
            //var old = db.Rooms.Find(room.ID);
            //room.CreatedAt = old.CreatedAt;
            //db.Entry(old).State = EntityState.Detached;

            if (ModelState.IsValid)
            {
                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "Salle modifiée";
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Users, "ID", "LastName", room.UserID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", room.CategoryID);
            return View(room);
        }

        // GET: BackOffice/Rooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: BackOffice/Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.Rooms.Find(id);
            db.Rooms.Remove(room);
            db.SaveChanges();
            TempData["Message"] = "Salle supprimée";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddFile(int id, HttpPostedFileBase upload)
        {
            if (upload == null)
            {
                TempData["Message"] = "Aucun fichier selectionné";
                return RedirectToAction("Edit", new { id });
            }

            if (upload.ContentLength > 0)
            {
                var model = new RoomFile();

                model.RoomID = id;
                model.Name = upload.FileName;
                model.ContentType = upload.ContentType;

                using (var reader = new BinaryReader(upload.InputStream))
                {
                    model.Content = reader.ReadBytes(upload.ContentLength);
                }

                db.RoomFiles.Add(model);
                db.SaveChanges();
                TempData["Message"] = "Fichier ajouté";
                return RedirectToAction("Edit", new { id = model.RoomID });

            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
        // GET: BackOffice/Rooms/Delete/5

        public ActionResult DeleteFile(int id)
        {
            RoomFile roomfile = db.RoomFiles.Find(id);
            db.RoomFiles.Remove(roomfile);
            db.SaveChanges();
            TempData["Message"] = "Fichier supprimé";
            return RedirectToAction("Edit", new { id = roomfile.RoomID });
        }
    }
}

Roomax/Roomax/Controllers/SharedController.cs
using Roomax.Areas.BackOffice.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomax.Controllers
{
    public class SharedController : BaseController
    {
        // GET: Shared
        [ChildActionOnly]
        public ActionResult TopFive()
        {
            var rooms = db.Rooms.OrderByDescending(x => x.Price).Take(5);
            return View("_TopFive", rooms);
        }
    }
}

Roomax/Roomax/Areas/BackOffice/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BackOffice | @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Roomax.css" rel="stylesheet" />
</head>
<body>
    <div class="container ">
        <nav class="row navbar navbar-expand-lg bg-info">
            <ul class="nav">
                <li><h1 class="lead text-white">BackOffice</h1></li>
                <li><a href="@Url.Action("Index", "Dashboard")" class="col-2 text-white">Accueil BackOffice</a></li>
                <li><a href="@Url.Action("Index", "Home", new { area = "" })" class="col-2 text-white">App</a></li>
            </ul>
        </nav>

        @RenderBody()
    </div>
    <div class="container">
        <div class="row">
            <footer class="bg-info w-100">
                &copy; BACKOFFICE POEC Rouen 2018
            </footer>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("SectionScripts", false)
</body>
</html>

Roomax/Roomax/Areas/BackOffice/Views/Shared/_LayoutBO.cshtml
@{
    Layout = null;
    var user = Session["USER_BO"] as Roomax.Models.User;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BackOffice | @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Roomax.css" rel="stylesheet" />

</head>
<body>
    <div class="container ">
        
        @if (TempData["Message"] != null && !string.IsNullOrWhiteSpace(TempData["Message"].ToString()))
        {
            <div class="alert alert-@TempData["MessageType"].ToString()">@TempData["Message"].ToString()</div>
        }
        <nav class="navbar navbar-expand-lg bg-info">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li><h1 class="lead text-white">BackOffice</h1></li>
                    <li><a href="@Url.Action("Index", "Dashboard")" class="col-2 text-white">Accueil BackOffice</a></li>
                    <li><a href="@Url.Action("Index", "Home", new { area = "" })" class="col-2 text-white">App</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Salles</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item " href="@Url.Action("Index", "Rooms")">Voir les Salles</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Categories")">Voir les Catégories</a>
                        </div>
                    </li>
                </ul>
                <span class="navbar-text">
                    Bonjour @user.FirstName @user.LastName
                    <a href="@Url.Action("Logout", "Authentication")" class="col-2 text-white">Deconnexion</a>
                </span>
            </div>
        </nav>

        @RenderBody()
    </div>
    <div class="container">
        <div class="row">
            <footer class="bg-info w-100">
                &copy; BACKOFFICE POEC Rouen 2018
            </footer>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("SectionScripts", false)
</body>
</html>